version: 2

sources:
  - name: gz_raw_data
    database: platinum-form-429314-q7
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
      - name: raw_gz_product
      - name: raw_gz_ship
